### ISSUE TITLE
Choose a better name.

### ISSUE THREAD

**Issue by bwinton** [FirefoxUX/product-identity#1]
I suggest `product-identity` so that we aren't limited to assets, or better yet `branding`! 😉

**Comment by aminalhazwani** [comment]
I like @bwinton suggestion here, personally I would even take a step further and call it just `brand`. I believe it makes the repo even more future-friendly rather than `product-identity-assets`.

**Comment by brassy-** [comment]
I think `product-identity` is just fine.

**Comment by aminalhazwani** [comment]
@bwinton feel free to rename it and close this issue!

**Comment by bwinton** [comment]
Fixed! 🙂
