### ISSUE TITLE
Add Firefox Focus Beta and Nightly logos?

### ISSUE THREAD

**Issue by alrra** [FirefoxUX/product-identity#10]
Ref: https://github.com/mozilla-mobile/focus-android/wiki/Release-tracks#nightly

**Comment by bwinton** [comment]
Makes sense to me. Did you want to ask the Focus people on IRC if they can attach icons to this issue, and I'll see about getting them imported? (Or you could submit a PR. 😉)

**Comment by aminalhazwani** [comment]
iirc those logos were lately added and didn't go through Photon polish, let me follow up on that!

**Comment by alrra** [comment]
> let me follow up on that!

@aminalhazwani Thanks!

**Comment by aminalhazwani** [comment]
Posting this for when we are ready to update the repository https://github.com/mozilla-mobile/focus-android/issues/2818#issuecomment-405799996
