### ISSUE TITLE
SVG icons and librsvg

### ISSUE THREAD

**Issue by nclm** [FirefoxUX/product-identity#5]
The SVG icons seem to cause a render error with `librsvg`, and therefore appear all black on Mediawiki powered websites and the GNOME desktop environment. For Wikimedia projects, we re-exported them from the Illustrator files using inline styles instead of an internal stylesheet, and the workaround works fine. https://commons.wikimedia.org/wiki/Category:Mozilla_Firefox_logos

**Comment by aminalhazwani** [comment]
I could probably fix this, I'll look into it!
